data:
  path: data/Crop_recommendation.csv
  test_size: 0.2
  random_state: 42

model:
  n_estimators: 100
  max_depth: 10
  min_samples_split: 2
  min_samples_leaf: 1
  random_state: 42

mlflow:
  experiment_name: npk-crop-recommendation
  tracking_uri: mlruns
